import { Config } from "./types/config";

/** Minutes to milliseconds */
const minutes = (_: number) => _ * 60 * 1000;

const multiply = (factor: number) => (_: number) => factor * _;

export default {
    school: {
        classes: [
            "10a",
            "10b",
            "10c",
            "10d",
            "5a",
            "5b",
            "5c",
            "5d",
            "5e",
            "6a",
            "6b",
            "6c",
            "6d",
            "6e",
            "7a",
            "7b",
            "7c",
            "7d",
            "8a",
            "8b",
            "8c",
            "8d",
            "9a",
            "9b",
            "9c",
            "9d",
            "j1",
            "j2",
            "lehrer",
        ],
    },
    currencies: {
        "plancko-digital": {
            name: "Plancko Digital",
            short: "PLK-D",
            symbol: "Ᵽ",
            decimals: 0,
            conversion: {
                "plancko-analog": multiply(1),
            },
        },
        "plancko-analog": {
            name: "Plancko Analog",
            short: "PLK-A",
            symbol: "Ᵽ",
            decimals: 0,
            conversion: {
                "plancko-digital": multiply(1),
            },
        },
    },
    mainCurrency: "plancko-digital",
    roles: {
        stateBankAccountId: "",

        adminCitizenIds: [],
        teacherCitizenIds: [
            "ass",
            "aub",
            "bal",
            "beg",
            "bei",
            "ben",
            "bhd",
            "bir",
            "bit",
            "bkf",
            "bmn",
            "bnk",
            "bot",
            "btz",
            "böm",
            "bür",
            "cor",
            "dau",
            "dmz",
            "don",
            "dos",
            "ebt",
            "egt",
            "esb",
            "ess",
            "fin",
            "fsl",
            "fss",
            "ftz",
            "fvr",
            "gal",
            "gln",
            "gnr",
            "grf",
            "gro",
            "hac",
            "hay",
            "her",
            "hff",
            "hfn",
            "hng",
            "how",
            "hvl",
            "hym",
            "häf",
            "hön",
            "hüm",
            "ign",
            "int",
            "job",
            "kal",
            "kbr",
            "kiz",
            "kli",
            "kls",
            "knl",
            "kre",
            "ktm",
            "kur",
            "kär",
            "lau",
            "lbe",
            "mai",
            "mch",
            "met",
            "mik",
            "mim",
            "moa",
            "mür",
            "not",
            "peo",
            "pfi",
            "pil",
            "prz",
            "ric",
            "rit",
            "rwl",
            "sar",
            "scr",
            "sei",
            "sgr",
            "shu",
            "skl",
            "sls",
            "snk",
            "snv",
            "soe",
            "sol",
            "soy",
            "sta",
            "ste",
            "tob",
            "unt",
            "vgt",
            "wie",
            "znd",
        ],

        warehouseCompanyId: "",
        bankCompanyId: "008",
        borderControlCompanyId: "004",
        taxOfficeCompanyId: "002",
        policeCompanyId: "005",
        policiticsCompanyId: "",
    },
    openingHours: {
        dates: ["2024-07-15", "2024-07-16", "2024-07-17", "2024-07-18"],
        open: "08:00:00+02:00",
        close: "16:00:00+02:00",
        timezone: "+02:00",
    },
    guestInitialBalance: 10,
    server: {
        url: "https://www.planckbank.com/graphql",
        host: "127.0.0.1",
        port: 4000,
        trustedOperations: [
            "59ef8dcaec0bc1ef1a87b7eeb9e5d9d1fe80899d92c7311f70eacbaa39ba3d6b",
        ],
    },
    database: {
        file: "database.sqlite3",
        backup: {
            dir: "__backup__/database",
            file: () => `database-backup-${new Date().toISOString()}.sqlite3`,
            interval: minutes(10),
        },
        allowRawSql: false,
    },
    flags: {
        changeTransactionClerk: false,
    },
} satisfies Config<"plancko-digital" | "plancko-analog"> as Config;
